export const Passion = {
  "Writing/Blogging": "Writing/Blogging",
  Baking: "Baking",
  "Refinishing furniture": "Refinishing furniture",
  "Flea Market Shopping": "Flea Market Shopping",
  Catering: "Catering",
  "Making Music": "Making Music",
  "Tapping Maple Trees": "Tapping Maple Trees",
  Bartending: "Bartending",
  "Wine Making": "Wine Making",
  "Playing the Stock Market": "Playing the Stock Market",
  "Taking Paid Surveys": "Taking Paid Surveys",
  Beekeeping: "Beekeeping",
  "Public Speaking": "Public Speaking",
  Programming: "Programming",
  "Proofreading and Editing": "Proofreading and Editing",
  Coding: "Coding",
  Tattooing: "Tattooing",
  "Performing Stand Up Comedy": "Performing Stand Up Comedy",
  "Drive Others Around": "Drive Others Around",
  "Graphic Design": "Graphic Design",
  "Making T,Shirts": "Making T,Shirts",
  "Becoming a Fitness Instructor": "Becoming a Fitness Instructor",
  "Starting a YouTube Channel": "Starting a YouTube Channel",
  "Being a Handyman": "Being a Handyman",
  "Decorating Homes": "Decorating Homes",
  "Reviewing Things": "Reviewing Things",
  "Pet Sitting": "Pet Sitting",
  "Flipping Items": "Flipping Items",
  "Becoming a Local Guide": "Becoming a Local Guide",
  "Pursuing Credit Card Rewards": "Pursuing Credit Card Rewards",
  "Social Media": "Social Media",
  "Buying and Selling": "Buying and Selling",
  "Credit Card Collecting": "Credit Card Collecting",
  "Creating and/or Editing Videos": "Creating and/or Editing Videos",
  "Giving Advice or Opinions": "Giving Advice or Opinions",
  "Create or sell pet clothing": "Create or sell pet clothing",
  "Create and sell gourmet pet treats": "Create and sell gourmet pet treats",
  Engravings: "Engravings",
  "Computer Technician": "Computer Technician",
  "Auto detailing": "Auto detailing",
  "Teaching and Tutoring Music": "Teaching and Tutoring Music",
  "Auto Customization": "Auto Customization",
  "Fitness or Yoga trainer": "Fitness or Yoga trainer",
  "Website optimization": "Website optimization",
  "Search engine marketing": "Search engine marketing",
  "Screen printing": "Screen printing",
  "Home staging": "Home staging",
  "Financial planning": "Financial planning",
  "Working On Cars": "Working On Cars",
  "Life coaching": "Life coaching",
  "Cartooning & Animation": "Cartooning & Animation",
  "Writing Music": "Writing Music",
  "Tutoring Children": "Tutoring Children",
  "Flower arranging": "Flower arranging",
  Couponing: "Couponing",
  "Mobile Technician": "Mobile Technician",
  "Coaching Local Sports": "Coaching Local Sports",
  Bicycling: "Bicycling",
  "Arts and Crafts": "Arts and Crafts",
  Genealogy: "Genealogy",
  "Rock Painting": "Rock Painting",
  "Making time capsules": "Making time capsules",
  "Dog Training": "Dog Training",
  "Road Biking": "Road Biking",
  Meditation: "Meditation",
  Walking: "Walking",
  "Candle making": "Candle making",
  Beachcombing: "Beachcombing",
  "Learn to Sew": "Learn to Sew",
  "Cash Flow Planning": "Cash Flow Planning",
  "Taking free online classes": "Taking free online classes",
  "Magic Tricks & Card Tricks": "Magic Tricks & Card Tricks",
  "Keep abreast of news and current affairs":
    "Keep abreast of news and current affairs",
  "Watch documentaries": "Watch documentaries",
  "Guerrilla gardening": "Guerrilla gardening",
  "Learn about philosophy": "Learn about philosophy",
  "Urban fruit picking": "Urban fruit picking",
  Minimalism: "Minimalism",
  Journaling: "Journaling",
  "Go To Free Community Events": "Go To Free Community Events",
  "Fostering Animals": "Fostering Animals",
  "Become a Wikipedia editor": "Become a Wikipedia editor",
  Decluttering: "Decluttering",
  Upcycling: "Upcycling",
  Reading: "Reading",
  "Making Miniatures": "Making Miniatures",
  Singing: "Singing",
  Tatebanko: "Tatebanko",
  Quilling: "Quilling",
  "Container Gardening": "Container Gardening",
  Archaeology: "Archaeology",
  "Playing Chess": "Playing Chess",
  "Circuits Training": "Circuits Training",
  "Learning how to DIY": "Learning how to DIY",
  Sudoku: "Sudoku",
  "Participate in trivia contests": "Participate in trivia contests",
  Noodling: "Noodling",
  "Attend Renaissance fairs": "Attend Renaissance fairs",
  "Feng Shui Decorating": "Feng Shui Decorating",
  "Plan walking tours": "Plan walking tours",
  Crabbing: "Crabbing",
  Boxing: "Boxing",
  "Dog Walking": "Dog Walking",
  "Organize a neighborhood clean,up": "Organize a neighborhood clean,up",
  "Shell fishing": "Shell fishing",
  "Fossil hunting": "Fossil hunting",
  Foraging: "Foraging",
  "Travel Hacking": "Travel Hacking",
  Lomography: "Lomography",
  "Learn how to make string figures": "Learn how to make string figures",
  Origami: "Origami",
  "Martial Arts": "Martial Arts",
  "Working out": "Working out",
  "Practicing Survival Skills": "Practicing Survival Skills",
  "Adventure Running": "Adventure Running",
  "Improving Your Memory": "Improving Your Memory",
  "Metal Working": "Metal Working",
  "Hookah Smoking": "Hookah Smoking",
  Caving: "Caving",
  "Weight Lifting": "Weight Lifting",
  "Jogging/Training for Marathon": "Jogging/Training for Marathon",
  "Spear Fishing": "Spear Fishing",
  "Car Racing": "Car Racing",
  Offroading: "Offroading",
  "Firearm Enthusiast": "Firearm Enthusiast",
  Fencing: "Fencing",
  Bouldering: "Bouldering",
  Hunting: "Hunting",
  "Reviewing Gadgets": "Reviewing Gadgets",
  Woodworking: "Woodworking",
  "Building Electronics": "Building Electronics",
  Archery: "Archery",
  "Rock Climbing": "Rock Climbing",
  "Fly Fishing": "Fly Fishing",
  Flying: "Flying",
  "Shooting/Marksmanship": "Shooting/Marksmanship",
  "Becoming an Alcohol Connoisseur": "Becoming an Alcohol Connoisseur",
  Hiking: "Hiking",
  "Collecting Military Paraphernalia": "Collecting Military Paraphernalia",
  "Airplane Combat": "Airplane Combat",
  Architecture: "Architecture",
  "Base Jumping": "Base Jumping",
  "Beer Tasting": "Beer Tasting",
  Barbecuing: "Barbecuing",
  "Boat Making": "Boat Making",
  "Community Activism": "Community Activism",
  "Robot Making": "Robot Making",
  "Pipe Making": "Pipe Making",
  Racquetball: "Racquetball",
  "Smoking Meat": "Smoking Meat",
  "Whisky Tasting": "Whisky Tasting",
  "Start Ground Hopping": "Start Ground Hopping",
  "Chainsaw Carving": "Chainsaw Carving",
  "Start An Allotment": "Start An Allotment",
  "Anti,Gravity Cocooning": "Anti,Gravity Cocooning",
  LudoSport: "LudoSport",
  "Retro Gaming": "Retro Gaming",
  "Cliff Diving": "Cliff Diving",
  "Amateur Geology": "Amateur Geology",
  Audiophile: "Audiophile",
  "Beat Box": "Beat Box",
  "Break Dancing": "Break Dancing",
  "Tomahawk/Hatchet Throwing": "Tomahawk/Hatchet Throwing",
  "Ice Fishing": "Ice Fishing",
  Kitesurfing: "Kitesurfing",
  Motocross: "Motocross",
  Paragliding: "Paragliding",
  "Tequila Tasting": "Tequila Tasting",
  "Skeet Shooting": "Skeet Shooting",
  "Storm Chasing": "Storm Chasing",
  "Orienteering Sports": "Orienteering Sports",
  "Jet sprint boat racing": "Jet sprint boat racing",
  "Drag boat racing": "Drag boat racing",
  Whittling: "Whittling",
  Yoga: "Yoga",
  Snorkeling: "Snorkeling",
  "Touring Wineries": "Touring Wineries",
  Massage: "Massage",
  Babysitting: "Babysitting",
  Squash: "Squash",
  "Wine/Cheese Tasting": "Wine/Cheese Tasting",
  "Ballroom dancing": "Ballroom dancing",
  "Board Game Club": "Board Game Club",
  Volunteering: "Volunteering",
  Sailing: "Sailing",
  Tennis: "Tennis",
  "Starting an Etsy or eBay Store": "Starting an Etsy or eBay Store",
  "Star Gazing": "Star Gazing",
  Homesteading: "Homesteading",
  Canoeing: "Canoeing",
  Bowling: "Bowling",
  "Entertaining & Event Hosting": "Entertaining & Event Hosting",
  "Learning a Foreign Language": "Learning a Foreign Language",
  "Recipe Creation": "Recipe Creation",
  "People Watching": "People Watching",
  Picnicking: "Picnicking",
  Acroyoga: "Acroyoga",
  "Lamp making": "Lamp making",
  Dancing: "Dancing",
  "Chocolate Tasting": "Chocolate Tasting",
  "Salsa dancing": "Salsa dancing",
  Pottery: "Pottery",
  Badminton: "Badminton",
  "Theme night dates": "Theme night dates",
  "Self,Care": "Self,Care",
  "World Record Breaking": "World Record Breaking",
  Renovating: "Renovating",
  "Weekend Adventuring": "Weekend Adventuring",
  "Hosting Dinner Parties": "Hosting Dinner Parties",
  "Road Trips": "Road Trips",
  Cosplaying: "Cosplaying",
  "Self Defense": "Self Defense",
  Zumba: "Zumba",
  Cooking: "Cooking",
  Drawing: "Drawing",
  "Learning a New Sport": "Learning a New Sport",
  "Flying Model Planes": "Flying Model Planes",
  "Model Ship Building": "Model Ship Building",
  "Sculpt with Clay/ Playdough": "Sculpt with Clay/ Playdough",
  "Collecting Seashells": "Collecting Seashells",
  "Beach / Sand Building": "Beach / Sand Building",
  "Nature Walk": "Nature Walk",
  "Zoo Visits": "Zoo Visits",
  "Solving Mazes": "Solving Mazes",
  "Balloon Twisting": "Balloon Twisting",
  "Collecting Stickers": "Collecting Stickers",
  "Collecting Leaves": "Collecting Leaves",
  Puppetry: "Puppetry",
  "Playing T,Ball": "Playing T,Ball",
  "Mini Golf": "Mini Golf",
  "Playing Soccer": "Playing Soccer",
  "Finger Painting": "Finger Painting",
  "Collecting Stamps": "Collecting Stamps",
  Coloring: "Coloring",
  "Lego Building/Assembling": "Lego Building/Assembling",
  "Doll making": "Doll making",
  "Making bird feeders and birdhouses": "Making bird feeders and birdhouses",
  "Insect interest": "Insect interest",
  Crocheting: "Crocheting",
  "Flower pressing": "Flower pressing",
  Felting: "Felting",
  Trekking: "Trekking",
  Knitting: "Knitting",
  Skating: "Skating",
  "Speed Cubing (Rubix Cube)": "Speed Cubing (Rubix Cube)",
  "Creating family trees": "Creating family trees",
  "Story,writing": "Story,writing",
  "Collecting Baseball cards": "Collecting Baseball cards",
  Tapestry: "Tapestry",
  "Pencil sketching": "Pencil sketching",
  "Comic book art": "Comic book art",
  "Jewellery making": "Jewellery making",
  "Doing science experiments": "Doing science experiments",
  "Flower making": "Flower making",
  "Learning How to Play Musical Instruments":
    "Learning How to Play Musical Instruments",
  Juggling: "Juggling",
  "Kite Flying": "Kite Flying",
  "Collecting Marbles": "Collecting Marbles",
  "Roller blading": "Roller blading",
  "Collage making": "Collage making",
  Slingshots: "Slingshots",
  "Paper Mache": "Paper Mache",
  "Making bookmarks": "Making bookmarks",
  "Making key holders": "Making key holders",
  Skateboarding: "Skateboarding",
  "Animal craft": "Animal craft",
  Acrobatics: "Acrobatics",
  "Jump Roping": "Jump Roping",
  "Color Guard": "Color Guard",
  Cheerleading: "Cheerleading",
  Baseball: "Baseball",
  Basketball: "Basketball",
  "Baton Twirling": "Baton Twirling",
  Scouting: "Scouting",
  "RC Model Racing": "RC Model Racing",
  "Stone Skipping": "Stone Skipping",
  Gymnastics: "Gymnastics",
  "Producing Electronic Music": "Producing Electronic Music",
  "Book Clubs": "Book Clubs",
  "Coffee Roasting": "Coffee Roasting",
  Airbrushing: "Airbrushing",
  Gunsmithing: "Gunsmithing",
  Pinochle: "Pinochle",
  Calligraphy: "Calligraphy",
  "Chocolate Making": "Chocolate Making",
  Ceramics: "Ceramics",
  Scrapbooking: "Scrapbooking",
  Fishkeeping: "Fishkeeping",
  "Soap Making": "Soap Making",
  "Knife Making": "Knife Making",
  Dandyism: "Dandyism",
  "Collecting Model Trains": "Collecting Model Trains",
  "War Gaming": "War Gaming",
  "Making Your Own Hot Sauce": "Making Your Own Hot Sauce",
  Poker: "Poker",
  "Playing Darts": "Playing Darts",
  Sculpting: "Sculpting",
  Lockpicking: "Lockpicking",
  "Watch making": "Watch making",
  "Jam Making": "Jam Making",
  Floristry: "Floristry",
  "Ghost Hunting": "Ghost Hunting",
  "3D Printing and Physibles": "3D Printing and Physibles",
  Macrame: "Macrame",
  Knapping: "Knapping",
  Lacemaking: "Lacemaking",
  Lapidary: "Lapidary",
  "Book Restoration": "Book Restoration",
  Podcasting: "Podcasting",
  "Table Tennis": "Table Tennis",
  "Yo,Yoing": "Yo,Yoing",
  "Reef aquarium": "Reef aquarium",
  Bookbinding: "Bookbinding",
  "Building Dollhouses": "Building Dollhouses",
  Conworlding: "Conworlding",
  Dominoes: "Dominoes",
  "Matchstick Modeling": "Matchstick Modeling",
  Impersonations: "Impersonations",
  Inventing: "Inventing",
  "Kitchen Chemistry": "Kitchen Chemistry",
  Knotting: "Knotting",
  "Playing Pool/Darts/Foosball": "Playing Pool/Darts/Foosball",
  "Making Model Cars": "Making Model Cars",
  "Tarot Reading": "Tarot Reading",
  "Sushi Making": "Sushi Making",
  "Scale Miniature Building": "Scale Miniature Building",
  "Collecting Diecast Cars": "Collecting Diecast Cars",
  "Building ships in bottles": "Building ships in bottles",
  Poetry: "Poetry",
  Beatboxing: "Beatboxing",
  "Bridge Building": "Bridge Building",
  Glowsticking: "Glowsticking",
  Tatting: "Tatting",
  Storytelling: "Storytelling",
  Embroidery: "Embroidery",
  "Crossword Puzzles": "Crossword Puzzles",
  ventriloquism: "ventriloquism",
  solitaire: "solitaire",
  "pet grooming": "pet grooming",
  "fruit carving": "fruit carving",
  "pencil carving": "pencil carving",
  "eggshell carving": "eggshell carving",
  "creating video tutorials": "creating video tutorials",
  "Urban Exploration": "Urban Exploration",
  "Tower Running": "Tower Running",
  Camping: "Camping",
  Surfing: "Surfing",
  "Laser tag": "Laser tag",
  "Video Games": "Video Games",
  Windsurfing: "Windsurfing",
  Airsoft: "Airsoft",
  Swimming: "Swimming",
  "Scuba Diving": "Scuba Diving",
  Paintballing: "Paintballing",
  "Drone Flying": "Drone Flying",
  "Ultimate Frisbee": "Ultimate Frisbee",
  "Trail running": "Trail running",
  "Competitive Eating": "Competitive Eating",
  "Collect Trainers": "Collect Trainers",
  Traveling: "Traveling",
  Wakeboarding: "Wakeboarding",
  "Water Ski": "Water Ski",
  "Wingsuit Flying": "Wingsuit Flying",
  "Fire Poi": "Fire Poi",
  "Learning Sign Language": "Learning Sign Language",
  Sandboarding: "Sandboarding",
  "River Rafting": "River Rafting",
  Running: "Running",
  Rapping: "Rapping",
  "Parkour – Freerunning": "Parkour – Freerunning",
  Parachuting: "Parachuting",
  Airsofting: "Airsofting",
  Boomerangs: "Boomerangs",
  "Go Kart Racing": "Go Kart Racing",
  Lacrosse: "Lacrosse",
  "Starting a Band": "Starting a Band",
  Powerboking: "Powerboking",
  Wrestling: "Wrestling",
  "Flying Drones": "Flying Drones",
  Ziplining: "Ziplining",
  "Grip Strength": "Grip Strength",
  "Field hockey": "Field hockey",
  Rugby: "Rugby",
  "Speed skating": "Speed skating",
  "Flag Football": "Flag Football",
  "Beach Volleyball": "Beach Volleyball",
  "Writing Letters": "Writing Letters",
  "Frisbee Golf – Frolf": "Frisbee Golf – Frolf",
  "Knife Throwing": "Knife Throwing",
  Skimboarding: "Skimboarding",
  "Dragon boat racing": "Dragon boat racing",
  "Cross Country Running": "Cross Country Running",
  "Fell Running": "Fell Running",
  "Track Cycling": "Track Cycling",
  "Surf lifesaving": "Surf lifesaving",
  Photography: "Photography",
  Blacksmithing: "Blacksmithing",
  Mountaineering: "Mountaineering",
  Backpacking: "Backpacking",
  "Sports – Refereeing": "Sports – Refereeing",
  "Horseback Riding": "Horseback Riding",
  Distilling: "Distilling",
  Landscaping: "Landscaping",
  "Stone Working": "Stone Working",
  Skydiving: "Skydiving",
  "Cave Diving": "Cave Diving",
  "Discover microscopy": "Discover microscopy",
  "Model Rockets": "Model Rockets",
  Papermaking: "Papermaking",
  Gnoming: "Gnoming",
  "Tour Skating": "Tour Skating",
  "Skiing/Snowboarding": "Skiing/Snowboarding",
  "Home Brewing": "Home Brewing",
  "Furniture Making": "Furniture Making",
  "Metal Detecting": "Metal Detecting",
  Geocaching: "Geocaching",
  "Becoming A Film Buff": "Becoming A Film Buff",
  "Treasure Hunting": "Treasure Hunting",
  "Glass blowing": "Glass blowing",
  "Organize fundraising": "Organize fundraising",
  "Mountain Biking": "Mountain Biking",
  "Collecting Comic Books": "Collecting Comic Books",
  "Neuro Linguistic Programming": "Neuro Linguistic Programming",
  "Gun Collecting": "Gun Collecting",
  "Speed Reading": "Speed Reading",
  Snowmobiling: "Snowmobiling",
  "Shark Diving": "Shark Diving",
  Pyrotechnics: "Pyrotechnics",
  Painting: "Painting",
  Letterboxing: "Letterboxing",
  "Hang Gliding": "Hang Gliding",
  Croquet: "Croquet",
  "Aircraft Spotting": "Aircraft Spotting",
  "Fly Tying": "Fly Tying",
  "Four Wheeling": "Four Wheeling",
  Herping: "Herping",
  Grilling: "Grilling",
  "Becoming a Rail Fan": "Becoming a Rail Fan",
  "Slack Lining": "Slack Lining",
  "Tool Collecting": "Tool Collecting",
  "Building Tesla Coils": "Building Tesla Coils",
  "Surf Fishing": "Surf Fishing",
  "Stamp Collecting": "Stamp Collecting",
  "Helping the Homeless": "Helping the Homeless",
  Motorcycling: "Motorcycling",
  "Dumpster Diving": "Dumpster Diving",
  Falconry: "Falconry",
  "Hot Air Ballooning": "Hot Air Ballooning",
  "Dog Sport": "Dog Sport",
  "Bicycle Polo": "Bicycle Polo",
  "Sand art": "Sand art",
  "Sculling or Rowing": "Sculling or Rowing",
  Astronomy: "Astronomy",
  "Boat racing": "Boat racing",
  "Outrigger Canoe racing": "Outrigger Canoe racing",
  Kicksled: "Kicksled",
  Skijoring: "Skijoring",
  "Kinetic sculpture racing": "Kinetic sculpture racing",
  Polo: "Polo",
  "Leather Making": "Leather Making",
  "Rock and Mineral Collecting": "Rock and Mineral Collecting",
  "Collecting Sea glass": "Collecting Sea glass",
  Upholstery: "Upholstery",
  Woodburning: "Woodburning",
  "RV Travelling": "RV Travelling",
  "Whale watching": "Whale watching",
  Gardening: "Gardening",
  Golf: "Golf",
  "Art collecting": "Art collecting",
  "Food Preservation (Pickling": "Food Preservation (Pickling",
  "Canning)": "Canning)",
  "Using Ham Radio": "Using Ham Radio",
  "Taking Part Historical Reenactments": "Taking Part Historical Reenactments",
  "Museum/Art Gallery Hopping": "Museum/Art Gallery Hopping",
  "Coin Collecting": "Coin Collecting",
  "Infuse Alcohol": "Infuse Alcohol",
  "Being A Cigar Aficionado": "Being A Cigar Aficionado",
  "Record Collecting": "Record Collecting",
  "Being A History Buff": "Being A History Buff",
  "Terrarium Making": "Terrarium Making",
  Farming: "Farming",
  Aquascaping: "Aquascaping",
  "Growing Bonsais": "Growing Bonsais",
  Meteorology: "Meteorology",
  "Found a charity group": "Found a charity group",
  Cartography: "Cartography",
  Taxidermy: "Taxidermy",
  Astrology: "Astrology",
  Cryptography: "Cryptography",
  Graphology: "Graphology",
  "Tea Drinking": "Tea Drinking",
  Fishing: "Fishing",
  "Tai Chi": "Tai Chi",
  "Palm Reading": "Palm Reading",
  "Music Memorabilia": "Music Memorabilia",
  "Butterfly Watching": "Butterfly Watching",
  Gyotaku: "Gyotaku",
  "Tombstone Rubbing": "Tombstone Rubbing",
  Trainspotting: "Trainspotting",
  "Bird Watching": "Bird Watching",
  "Rock Balancing": "Rock Balancing",
  Curling: "Curling",
  "Fish Tournaments": "Fish Tournaments",
  "Cloud Watching": "Cloud Watching",
  Deltiology: "Deltiology",
  Antiquing: "Antiquing",
  Exercising: "Exercising",
  "Brewing beer": "Brewing beer",
  "Restoring furniture": "Restoring furniture",
  "Raising animals": "Raising animals",
  "Leaf Collecting and Pressing": "Leaf Collecting and Pressing",
  "Carpet Weaving": "Carpet Weaving",
  "Freelance photography": "Freelance photography",
  Investing: "Investing",
  "Fantasy Sports": "Fantasy Sports",
  "Do improv": "Do improv",
  Chandlery: "Chandlery",
  "Wheel throwing": "Wheel throwing",
  "Survival Prepping": "Survival Prepping",
  "Build model rockets": "Build model rockets",
  "Silver Making": "Silver Making",
  "Sky Diving": "Sky Diving",
  "Tattoo Designing": "Tattoo Designing",
  "Vinyl Collecting": "Vinyl Collecting",
  "Board surfing": "Board surfing",
  "Leather Tooling": "Leather Tooling",
  "Puppet making": "Puppet making",
  "Digital scrapbooking": "Digital scrapbooking",
  Karate: "Karate",
  "Cake decorating": "Cake decorating",
  "Star watching": "Star watching",
  "Air gardening": "Air gardening",
  Freediving: "Freediving",
  Beadwork: "Beadwork",
  Quilting: "Quilting",
  "Cookie decorating": "Cookie decorating",
  "Anagram Designing": "Anagram Designing",
  "Latte Art": "Latte Art",
  "Wall Art": "Wall Art",
  "Music Writing": "Music Writing",
  "Currency Collecting": "Currency Collecting",
  Kayaking: "Kayaking",
  "Cheese making": "Cheese making",
  "Nature painting": "Nature painting",
  Shopping: "Shopping",
  "Exotic pets": "Exotic pets",
  Mixology: "Mixology",
};
